@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Users
Person(talentManagementUser, "Talent manager")

'Dependencies
System(talent_management_system, "Talent Management System", "REST API")

' ioet feature flag library
Container(ff, "Feature Flag Library", "Code encapsulation and context-aware switching via toggle points and routers, managed via toggle configuration data")

' User relations
Rel(talentManagementUser, talent_management_system, "Executes any of the talent management system use cases", "")

' Systems relations
    Rel(ff, talent_management_system, "Executes an encapsulated piece of code based on toggles' context and type", "")
    Rel(talent_management_system, ff, "Defines code paths under one or more feature toggles", "system dependency")
    Rel(ff, talent_management_system, "Reads toggle configuration data from a local or remote source", "")
    Rel(talent_management_system, ff, "Provides context data about the user", "system dependency")

@enduml